### ISSUE TITLE
Python 3.13: AttributeError: 'AdbConnection' object has no attribute '_finalizer'

### ISSUE THREAD

**Issue by dynamicsamurai816** [openatx/adbutils#165]
2025-05-06 13:08:49,517 - RunMainLoop - ERROR - Error starting scrcpy: 'AdbConnection' object has no attribute '_finalizer'
2025-05-06 13:08:49,520 - RunMainLoop - ERROR - Traceback (most recent call last):
  File "C:\Users\...\RunMainLoop.py", line 34, in run_main_loop
    processes["scrcpy"].start()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\...\scrcpy\core.py", line 222, in start
    self.__init_server_connection()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\...\scrcpy\core.py", line 131, in __init_server_connection
    self.__video_socket = self.device.create_connection(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        Network.LOCAL_ABSTRACT, "scrcpy"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\...\venv\Lib\site-packages\adbutils\_device.py", line 380, in create_connection
    c._finalizer.detach()
    ^^^^^^^^^^^^
AttributeError: 'AdbConnection' object has no attribute '_finalizer'


----

Am trying to use adbutils on Python 3.13. It works fine on Python 3.11, but I get this error on newer version

**Comment by codeskyblue** [comment]
It's a bug, thanks for reporting
